### ISSUE TITLE
格式化的方式

### ISSUE THREAD

**Issue by duchengyao** [metowolf/qqwry.ipdb#12]
请问格式化的方式 https://github.com/metowolf/qqwry.ipdb/tree/master/src/format 灵感来自哪里呀，或者有博客介绍吗？

我准备写一个python 版本的

谢谢^_^

**Comment by metowolf** [comment]
这里其实是不断试错得出来的，仍然会有一些数据会解析偏差，也欢迎共享思路～

**Comment by duchengyao** [comment]
@metowolf 

原来是这样～谢谢大佬的疯狂测试
