### ISSUE TITLE
packer.js测试中存在找不到索引的问题

### ISSUE THREAD

**Issue by mioshare** [metowolf/qqwry.ipdb#14]
1.2.2.0|1.2.2.255|16908800|16909055|亚洲|中国|北京|
1.2.4.0|1.2.4.7|16909312|16909319|亚洲|中国|北京|
1.2.4.9|1.2.5.255|16909321|16909823|亚洲|中国|北京|
1.2.8.0|1.2.8.255|16910336|16910591|亚洲|中国|北京|
1.4.4.0|1.4.4.255|17040384|17040639|亚洲|中国|北京|
1.8.0.0|1.8.101.255|17301504|17327615|亚洲|中国|北京|
我的数据格式如上面这样，需要转换ipipnet格式，在转换过程中，发现这两个地方，报了索引不存在问题
https://github.com/metowolf/qqwry.ipdb/blob/f2af07e6531fae6cd73bcbceec20c8d7b933e0b5/src/packer.js#L24

 https://github.com/metowolf/qqwry.ipdb/blob/f2af07e6531fae6cd73bcbceec20c8d7b933e0b5/src/packer.js#L114

我在前面都加了如下判断：
if(typeof(this.node[node])=="undefined"){
        this.node[node] = [null, null];
      }
不知道对整个数据有没有影响呢，对nodejs不太熟悉，望老师傅赐教

**Comment by SukkaW** [comment]
@mioshare 如果出现报错，说明你的 IP 段数据存在不连续或者有重复：

```
|   a   |
        |      |    b    |
```

```
|      a      |
     |         b        |
```

这样都是不允许的。

**Comment by mioshare** [comment]
谢谢回答，可能是数据不连续的问题，就需要每段ip需要预先要从小排到大连续排序吗

**Comment by SukkaW** [comment]
> 谢谢回答，可能是数据不连续的问题，就需要每段ip需要预先要从小排到大连续排序吗

在 pack 时不需要从小到大连续排序。

但是推荐先对数据源进行从小到大排序，并重点排查有重复和互相包含（例如 `1.0.0.0|1.0.0.255` 与 `1.0.0.128|1.0.1.10`，其中 1.0.0.128 ~ 1.0.0.255 这一段同时出现在了两行数据中）的数据。

**Comment by mioshare** [comment]
> > 谢谢回答，可能是数据不连续的问题，就需要每段ip需要预先要从小排到大连续排序吗
> 
> 在 pack 时不需要从小到大连续排序。
> 
> 但是推荐先对数据源进行从小到大排序，并重点排查有重复和互相包含（例如 `1.0.0.0|1.0.0.255` 与 `1.0.0.128|1.0.1.10`，其中 1.0.0.128 ~ 1.0.0.255 这一段同时出现在了两行数据中）的数据。

明白，谢谢
