### ISSUE TITLE
ipip.net 官方SDK解析生成的ipdb格式数据报错

### ISSUE THREAD

**Issue by vampire007** [metowolf/qqwry.ipdb#4]
您好，我按照您提供的packer方法，将文本格式转换为ipdb格式了，但是使用官方SDK进行解析的时候报错了。您这边能够提供一个文本格式转ipdb格式的使用Demo吗？

**Comment by SukkaW** [comment]
本项目即为从纯真 IP 库获取文本格式并在格式化后转为 ipdb 格式的 Demo。
关于 IPIP 官方 SDK 的解析问题请直接咨询 IPIP 的高春辉，我们无法提供任何关于 IPIP 官方 SDK 问题的解答。
