### ISSUE TITLE
qqwry.ipdb/src/format/ 惊呆了

### ISSUE THREAD

**Issue by itbdw** [metowolf/qqwry.ipdb#8]
你好我是 ip-database 的维护，最近在搜 qqwry ，搜到了这里

qqwry.ipdb/src/format/ 这个目录的数据怎么获得的呢，这么详尽的地址列表。佩服佩服

**Comment by SukkaW** [comment]
数据基于纯真 IP 数据库，我们自己编写了格式化和结构化、服务商和大学的匹配；我本人也是纯真 IP 数据库的数据活跃提交者之一。

**Comment by itbdw** [comment]
太赞了，冒昧问下，能否在ip-database项目里，选择性的使用这些数据呢

**Comment by SukkaW** [comment]
@itbdw 非常抱歉，**不能**。由于本项目 **没有指定任何开源协议**，项目 Contributors **保留** 对 **所有代码** 的 **所有权利**。

**Comment by itbdw** [comment]
好的好的，我自己去找一下国家区域划分
